FROM python:3.12-bookworm
WORKDIR /app
COPY requirements/backend-numpy.lock requirements/backend-numpy.lock
RUN python -m pip install --no-cache-dir -r requirements/backend-numpy.lock
COPY spaceship spaceship
COPY build build
EXPOSE 8080
CMD ["uvicorn", "spaceship.main:app", "--host", "0.0.0.0", "--port", "8080"]
