FROM golang:1.24-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags='-s -w' -o /out/fizzbuzz .

FROM scratch
COPY --from=build /out/fizzbuzz /fizzbuzz
EXPOSE 8080
ENTRYPOINT ["/fizzbuzz", "serve"]
